### PR TITLE
improve ssl generator

### PR DESCRIPTION
**Pull request by grosser**
- remove csr config since it is generated
- remove duplicated defaults from ssl.sh / fix $app not being found

@alex-leonhardt

### CODE REVIEW

**Review by alex-leonhardt — COMMENTED** [review]
I know `ssl/csr.conf` is being generated, however I'd like to keep it somewhere as an example so it's easier for a person to reason about what needs to be in that file. If you don't mind, could you move it somewhere sensible (e.g. `examples/csr.conf` or similar) instead of removing the file altogether?

**Comment by grosser** [comment]
then I'd rather just keep it there 🤷‍♂

**Comment by grosser** [comment]
updated

**Review by alex-leonhardt — APPROVED** [review]
👍 thanks!

**Pull request merged**
